services:
  weatherapp-api:
    image: weatherapp-api
    hostname: weatherapp-db
    build:
      context: .
      dockerfile: API.Dockerfile
    container_name: weatherapp-api
    restart: unless-stopped
    ports:
       - 8888:8888
    env_file:
      - ./.env
    logging:
      options:
        max-size: 10m
  weatherapp-db:
    image: weatherapp-db
    hostname: weatherapp-db
    build:
      context: .
      dockerfile: DB.Dockerfile
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_DBNAME}
    container_name: weatherapp-db
    restart: unless-stopped
    ports:
       - ${DB_PORT}:3306
    
